#epsilon: 0.026
epsilon_i: 0.0415
epsilon_f: 0.0415
nu_m_f: 0.83
nu_m_i: 0.83
#nu_m_i: 0.9594

# FCC stocastico: intervallo circa 0.959 - 0.9617
# FCC ham: intervallo circa 0.9575 - 0.96


#epsilon_f: 0.025
#epsilon_i: 0.0125
#nu_m_f: 0.5
#nu_m_i: 0.5
